require("dotenv").config({path:"./.env"})
const { Client } = require("pg")

const SQL = `

DROP TABLE inventory;
CREATE TABLE inventory (
    id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    partno VARCHAR(30),
    name TEXT,
    category VARCHAR(20),
    description TEXT,
    manufacturer VARCHAR(20),
    datasheet_url TEXT,
    specs JSONB -- This is the new column
);

INSERT INTO inventory (partno, name, category, description, manufacturer, datasheet_url, specs) VALUES
('ATMEGA328P-PU', 'ATmega328P Microcontroller', 'microcontroller', 'This 8-bit AVR RISC-based microcontroller combines 32KB ISP flash memory with read-while-write capabilities, 1KB EEPROM, 2KB SRAM, 23 general purpose I/O lines, 32 general purpose working registers, three flexible timer/counters with compare modes, internal and external interrupts, a serial programmable USART, a byte-oriented 2-wire serial interface, an SPI serial port, a 6-channel 10-bit A/D converter (8-channels in TQFP and QFN/MLF packages), and a programmable watchdog timer with internal oscillator. It operates between 1.8-5.5 volts.', 'Microchip Technology', 'https://www.microchip.com/wwwproducts/en/ATmega328P', '{"voltage": "5V", "flash_kb": 32, "ram_kb": 2, "clock_mhz": 16, "io_pins": 23}'),
('LM358N', 'LM358 Dual Op-Amp', 'opamp', 'The LM358 is a low-power, dual operational amplifier designed for a wide range of applications. It operates from a single power supply over a wide range of voltages or from dual power supplies, making it versatile. Key features include true differential inputs, a large output voltage swing, and low supply current drain, independent of the magnitude of the power supply voltage. It''s an excellent choice for general-purpose amplification, active filters, and various signal conditioning tasks where cost-effectiveness and reliability are key.', 'Texas Instruments', 'https://www.ti.com/product/LM358', '{"type": "Dual Op-Amp", "supply_voltage_v": "3-32", "gbw_mhz": 1, "slew_rate_v_us": 0.5}'),
('1N4007', '1N4007 Rectifier Diode', 'diode', 'The 1N4007 is a ubiquitous standard 1.0 Ampere silicon rectifier diode, renowned for its reliability and widespread use in power supplies, adapters, and other general-purpose rectification applications. It boasts a high maximum recurrent peak reverse voltage of 1000 Volts and a low forward voltage drop, ensuring efficient conversion of AC to DC. Its robust design and axial lead package make it easy to incorporate into through-hole designs for various electronic circuits requiring robust power conversion.', 'ON Semiconductor', 'https://www.onsemi.com/products/discretes-logic-and-fets/diodes/standard-rectifier-diodes/1n4007', '{"forward_current_a": 1, "reverse_voltage_v": 1000, "package": "DO-41"}'),
('CRCW080510K0FKEA', '10kΩ Resistor (SMD 0805)', 'resistor', 'This is a standard 10 kilo-ohm (10kΩ) surface mount device (SMD) thick film resistor, featuring the common 0805 package size. It is widely used in compact electronic circuits for current limiting, voltage division, and signal conditioning. With a 1% tolerance, it provides accurate resistance for most applications, offering stability and reliability in various operating conditions. Its small footprint makes it ideal for densely packed PCBs and miniaturized electronic designs across consumer and industrial sectors.', 'Vishay', 'https://www.vishay.com/docs/20035/crcw.pdf', '{"resistance_ohm": 10000, "tolerance_pct": 1, "power_w": 0.125, "package": "0805"}'),
('C0805C104K5RACTU', '0.1µF Ceramic Capacitor (SMD 0805)', 'capacitor', 'This is a 0.1 microfarad (0.1µF) multilayer ceramic chip capacitor (MLCC) in an 0805 SMD package. It is a general-purpose capacitor suitable for a wide array of applications including decoupling, bypassing, and filtering in power supply circuits and signal lines. Known for its small size, high reliability, and excellent frequency characteristics, it operates efficiently at up to 50 volts, making it a popular choice for digital and analog circuit designs requiring stable capacitance in a compact form factor.', 'KEMET', 'https://content.kemet.com/datasheets/KEM_C1001_MLCC_SMD_CommX7R.pdf', '{"capacitance_uf": 0.1, "voltage_v": 50, "dielectric": "X7R", "package": "0805"}'),
('ESP32-WROOM-32', 'ESP32 Wi-Fi/BT Module', 'microcontroller', 'The ESP32-WROOM-32 is a powerful, generic Wi-Fi + Bluetooth + BLE MCU module that targets a wide variety of applications. It features an ESP32-D0WDQ6 chip, 4MB of SPI flash, and integrates a dual-core 32-bit LX6 microcontroller. Its rich peripheral set, including UART, SPI, I2C, ADC, DAC, and touch sensors, along with robust connectivity, makes it ideal for IoT devices, smart home automation, industrial control, and wearable electronics, providing a cost-effective and versatile solution for embedded development.', 'Espressif Systems', 'https://www.espressif.com/sites/default/files/documentation/esp32-wroom-32_datasheet_en.pdf', '{"voltage": "3.3V", "connectivity": ["Wi-Fi", "Bluetooth"], "flash_mb": 4, "cores": 2}'),
('NE555P', 'NE555 Timer IC', 'ic', 'The NE555 is a highly stable integrated circuit capable of producing accurate time delays or oscillation. Designed for precision, it can operate in monostable (one-shot), astable (free-running), and bistable (flip-flop) modes. Its versatility allows it to be used in various applications such as pulse generation, sequential timing, LED flashers, tone generation, and simple DC-DC converters. It is a cornerstone component for hobbyists and professionals alike, known for its robustness and ease of implementation in timing-critical circuits.', 'ST Microelec.', 'https://www.st.com/resource/en/datasheet/ne555.pdf', '{"supply_voltage_v": "5-15", "package": "DIP-8", "function": "Timer", "frequency_range_hz": "0.001 to 500k"}'),
('BC547', 'BC547 NPN Transistor', 'transistor', 'The BC547 is a general-purpose NPN bipolar junction transistor (BJT) commonly used for switching and amplification in low-power applications. Its widespread availability, low cost, and standard TO-92 package make it a staple in hobbyist projects and educational kits. It offers good current gain and reliable performance for tasks such as driving small relays, switching LEDs, and basic audio amplification, making it a versatile component in a vast array of electronic circuits.', 'NXP Semicon.', 'https://www.nexperia.com/docs/data_sheet/BC547_SER.pdf', '{"type": "NPN", "collector_current_ma": 100, "collector_voltage_v": 45, "package": "TO-92", "gain_hfe": "200-800"}'),
('LED5MM-RED', '5mm Red LED', 'diode', 'This is a standard 5mm diffused round-top red LED (Light Emitting Diode), perfect for general indication purposes in various electronic projects. Its diffused lens provides a wide viewing angle, ensuring visibility from different perspectives. Operating at low current and voltage, it''s energy-efficient and easily integrated into circuits. Commonly used in power indicators, status lights, and decorative lighting, it offers a bright and long-lasting illumination solution for simple visual feedback.', 'Generic', 'https://www.sparkfun.com/datasheets/Components/LED/COM-09590-5mm-Red-LED.pdf', '{"color": "Red", "size_mm": 5, "forward_voltage_v": 2, "forward_current_ma": 20, "luminous_intensity_mcd": 150}'),
('MCP3008-I/P', 'MCP3008 ADC', 'ic', 'The MCP3008 is a 10-bit Analog-to-Digital Converter (ADC) that offers 8 input channels and communicates via the SPI interface. This allows microcontrollers without built-in ADCs, or those needing more channels or higher resolution, to easily read analog sensor data. Its simplicity, single-supply operation (2.7V to 5.5V), and widespread library support (especially for Arduino and Raspberry Pi) make it an extremely popular choice for interfacing analog sensors in embedded systems and data acquisition projects.', 'Microchip Technology', 'https://www.microchip.com/wwwproducts/en/MCP3008', '{"resolution_bits": 10, "channels": 8, "interface": "SPI", "supply_voltage_v": "2.7-5.5", "sampling_rate_ksps": 200}'),
('2N3904', '2N3904 NPN Transistor', 'transistor', 'The 2N3904 is a versatile general-purpose NPN bipolar junction transistor (BJT) widely utilized in low-power switching and amplification applications. Its robust design and standard TO-92 package ensure ease of integration into through-hole designs. Known for its reliability and cost-effectiveness, it serves as an excellent choice for tasks like signal amplification, driving small loads, and logic level shifting in a broad spectrum of electronic circuits, from educational projects to industrial controls.', 'Fairchild Semi.', 'https://www.onsemi.com/pub/Collateral/2N3904-D.PDF', '{"type": "NPN", "collector_current_ma": 200, "collector_voltage_v": 40, "package": "TO-92", "gain_hfe": "100-300"}'),
('470uF-50V', '470µF Electrolytic Capacitor', 'capacitor', 'This is a radial electrolytic capacitor with a capacitance of 470 microfarads (µF) and a voltage rating of 50 Volts. Electrolytic capacitors are commonly used in power supply circuits for filtering, smoothing, and energy storage due to their high capacitance values in a relatively small form factor. This particular component is suitable for applications requiring substantial charge storage and stable voltage regulation across various consumer and industrial electronic devices.', 'Rubycon', 'https://www.rubycon.com/wp-content/uploads/2021/07/us_yk.pdf', '{"capacitance_uf": 470, "voltage_v": 50, "type": "Electrolytic", "esr_ohm": 0.5, "package": "Radial"}'),
('AD8220ARZ', 'AD8220 Instrumentation Amp', 'opamp', 'The AD8220 is a high-performance, low-cost instrumentation amplifier offering excellent common-mode rejection and low noise, making it ideal for precision signal acquisition from sensors. It features a wide input range and single-supply operation, simplifying designs. Its robust input protection ensures reliable operation in harsh environments. Used in medical instrumentation, industrial process control, and data acquisition systems, it provides precise amplification for differential signals, converting them into single-ended outputs for further processing.', 'Analog Devices', 'https://www.analog.com/media/en/technical-documentation/data-sheets/AD8220.pdf', '{"gain_range": "1-1000", "supply_voltage_v": "5-36", "package": "SOIC-8", "offset_voltage_uv": 75}'),
('CRCW0603100RFKEA', '100Ω Resistor (SMD 0603)', 'resistor', 'This is a 100 Ohm surface mount (SMD) thick film resistor in a compact 0603 package size. Ideal for space-constrained designs, it provides accurate resistance for current limiting, pull-up/pull-down operations, and impedance matching. With a 1% tolerance, it offers reliable performance in various electronic circuits, from consumer electronics to industrial equipment, ensuring stable operation and precise signal control in high-density PCB layouts due to its miniature footprint.', 'Yageo', 'https://www.yageo.com/en/ProductDetail/CRCW0603100RFKEA', '{"resistance_ohm": 100, "tolerance_pct": 1, "power_w": 0.1, "package": "0603"}'),
('HC-SR04', 'Ultrasonic Sensor Module', 'sensor', 'The HC-SR04 ultrasonic sensor module provides 2cm to 400cm non-contact measurement functionality with a ranging accuracy that can reach 3mm. Operating at 5V, it is popular for its ease of use with microcontrollers like Arduino, providing a straightforward interface for distance measurement. It consists of an ultrasonic transmitter, receiver, and control circuit, making it perfect for robotic obstacle avoidance, distance ranging projects, and fluid level detection, offering a simple yet effective method for spatial awareness.', 'Generic', 'https://cdn.sparkfun.com/datasheets/Sensors/Proximity/HCSR04.pdf', '{"voltage": "5V", "range_cm": "2-400", "interface": "Digital I/O", "accuracy_mm": 3}'),
('TL072CP', 'TL072 Dual JFET Op-Amp', 'opamp', 'The TL072 is a low-noise, JFET-input operational amplifier featuring high input impedance, low input bias current, and high slew rate. Its dual configuration provides two independent op-amps in a single package, making it versatile for audio applications, active filters, and precision instrumentation where signal integrity and minimal noise are crucial. The JFET inputs ensure minimal current draw from the input signal source, maintaining signal fidelity across a wide frequency range.', 'Texas Instruments', 'https://www.ti.com/product/TL072', '{"type": "Dual JFET Op-Amp", "supply_voltage_v": "6-36", "gbw_mhz": 4, "slew_rate_v_us": 13}'),
('IRF540N', 'IRF540N Power MOSFET', 'transistor', 'The IRF540N is a N-channel power MOSFET designed for high-speed switching applications. It offers a low ON-resistance (RDS(on)) and high current capability, making it suitable for motor control, power supplies, and high-current switching circuits. Its robust design ensures reliability in demanding environments, providing efficient power management in various industrial and automotive applications. The TO-220 package allows for easy mounting and effective heat dissipation for optimal performance.', 'Infineon Tech.', 'https://www.infineon.com/dgdl/irf540n.pdf?fileId=5546d462533600a4015355c7097c191a', '{"type": "N-channel MOSFET", "drain_current_a": 33, "drain_voltage_v": 100, "r_ds_on_ohm": 0.044, "package": "TO-220"}'),
('PC817', 'PC817 Optocoupler', 'ic', 'The PC817 is a general-purpose single-channel phototransistor optocoupler. It provides electrical isolation between two circuits, using an infrared LED to transmit a signal to a phototransistor. This isolation is crucial in applications where sensitive low-voltage control circuits need to be safely separated from high-voltage power circuits, preventing ground loops and noise propagation. Commonly used in switch-mode power supplies, inverters, and home appliances for signal coupling and isolation.', 'Sharp', 'https://assets.sharp.eu/web/f_auto/original/product/documents/opto_PC817.pdf', '{"channels": 1, "isolation_voltage_v_rms": 5000, "current_transfer_ratio_pct": "50-600", "package": "DIP-4"}'),
('MAX232N', 'MAX232 RS-232 Transceiver', 'ic', 'The MAX232 is an integrated circuit that converts signals from an RS-232 serial port to signals suitable for use in TTL-compatible digital logic circuits. It includes a dual charge pump that enables it to operate from a single 5V power supply, generating ±10V for RS-232 signal levels. Essential for interfacing microcontrollers with PC serial ports, it''s widely used in embedded systems for debugging, data logging, and communication between different voltage domains.', 'Analog Devices', 'https://www.analog.com/media/en/technical-documentation/data-sheets/MAX232.pdf', '{"voltage_v": 5, "drivers": 2, "receivers": 2, "interface": "RS-232", "package": "DIP-16"}'),
('DS18B20', 'DS18B20 Digital Temp Sensor', 'sensor', 'The DS18B20 is a 1-Wire digital thermometer that measures temperature from -55°C to +125°C with ±0.5°C accuracy from -10°C to +85°C. Its 1-Wire interface allows multiple sensors to share a single data line, simplifying wiring. Each sensor has a unique 64-bit serial code, enabling multiple sensors to function on the same bus. Ideal for environmental monitoring, industrial control, and thermal management, offering robust and precise temperature readings in various conditions.', 'Maxim Integrated', 'https://datasheets.maximintegrated.com/en/ds/DS18B20.pdf', '{"type": "Digital", "temp_range_c": "-55 to 125", "accuracy_c": "0.5", "interface": "1-Wire"}'),
('LM7805', 'LM7805 Voltage Regulator', 'ic', 'The LM7805 is a fixed 5V positive voltage regulator, designed to provide a stable 5-volt output from a higher, unregulated DC input voltage. It is widely used in power supply circuits to convert an unregulated input to a stable output, protecting sensitive electronic components from voltage fluctuations. Its simplicity of use, built-in thermal overload, and short-circuit protection make it a reliable and essential component for various electronic applications requiring a regulated 5V power supply.', 'ST Microelec.', 'https://www.st.com/resource/en/datasheet/lm7805.pdf', '{"output_voltage_v": 5, "input_voltage_v": "7-25", "output_current_a": 1, "package": "TO-220"}'),
('MCP4725', 'MCP4725 DAC Module', 'ic', 'The MCP4725 is a 12-bit Digital-to-Analog Converter (DAC) with an I2C interface, capable of generating precise analog voltage outputs from digital input signals. It features an on-board EEPROM for non-volatile storage of DAC settings and a versatile operating voltage range. Ideal for generating analog waveforms, controlling motors, or dimming LEDs, it provides a simple and accurate way to convert digital values to analog voltages in embedded systems and control applications requiring fine analog resolution.', 'Microchip Technology', 'https://www.microchip.com/wwwproducts/en/MCP4725', '{"resolution_bits": 12, "interface": "I2C", "voltage_v": "2.7-5.5", "type": "DAC", "channels": 1}'),
('BME280', 'BME280 Env. Sensor', 'sensor', 'The BME280 is an integrated environmental sensor combining pressure, humidity, and temperature measurement functions. It offers high accuracy, low power consumption, and operates over I2C and SPI interfaces, making it ideal for weather stations, indoor navigation, and IoT applications. Its compact size and robust performance provide comprehensive environmental data, enabling precise atmospheric monitoring and control in various smart devices and connected systems.', 'Bosch Sensortec', 'https://www.bosch-sensortec.com/media/boschsensortec/downloads/datasheets/bst-bme280-ds002.pdf', '{"type": "Env.", "interface": ["I2C", "SPI"], "temp_accuracy_c": 0.5, "humidity_accuracy_pct": 3, "pressure_accuracy_hpa": 1}'),
('PL2303HX', 'PL2303HX USB to TTL', 'ic', 'The PL2303HX is a USB to TTL serial converter IC, essential for interfacing microcontroller projects with a computer via a USB port. It provides a reliable and cost-effective solution for creating a virtual COM port, enabling easy communication for programming, debugging, and data exchange. Commonly found in USB-to-serial adapter cables, it simplifies connections between TTL-level serial devices and modern computers lacking native serial ports, making development much more convenient.', 'Prolific', 'https://www.prolific.com.tw/UserFiles/files/PL2303HXD_Datasheet_v1.4.pdf', '{"interface": "USB to TTL", "voltage_v": 5, "package": "SSOP-28"}');

`;

async function main(){
    console.log("...seeding")
    const client = new Client({connectionString:process.env.DB})
    await client.connect()
    await client.query(SQL)
    await client.end()
    console.log("done")
}

main()